AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudreach-demo

  Template for Cloudreach Assesment 

Globals:
  Function:
    Timeout: 3

Resources:
  GpsTable:
    Type: AWS::Serverless::SimpleTable
    PrimaryKeyObject: 
      Name: id
      Type: String
    TableName: GpsTable

  RestApi2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GpsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref GpsTable
      Events:
        HotspotApi:
          Type: Api
          Properties:
            Method: GET
            Path: /hotspotdata
            RequestParameters:
              - method.request.querystring.longitude:
                  Required: true
              - method.request.querystring.latitude:
                  Required: true
    
  RestApi1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref GpsTable
      Events:
        PostData:
          Type: Api
          Properties:
            Method: POST
            Path: /hotspotdata

          



